language: java

jdk:
 - openjdk11

addons:
 sonarcloud:
  organization: "unimibsoftengcourse1920"
  token:
   secure: $SONAR_TOKEN

script:
 - mvn Backend/ProgettoAste clean verify sonar:sonar -Dsonar.projectKey=UnimibSoftEngCourse1920_progetto-aste-2-gruppo-aste-2
